apiVersion: apps/v1
kind: Deployment
metadata:
  name: sta-deployment
  labels:
    app: sta
spec:
  replicas: 1  # Number of Pods
  selector:
    matchLabels:
      app: sta
  template:
    metadata:
      labels:
        app: sta
    spec:
      containers:
      - name: sta-container
        image: yolomurphy/test:latest  # Replace 'latest' with the appropriate tag
        ports:
        - containerPort: 80  # Update to match your app's container port

---
apiVersion: v1
kind: Service
metadata:
  name: sta-service
  labels:
    app: sta
spec:
  selector:
    app: sta  # Matches the Deployment's label
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the Service
      targetPort: 80  # Port on the container
  type: ClusterIP  # Use LoadBalancer or NodePort if needed
